# Generated by Django 5.2.9 on 2025-12-28 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shared", "0003_client_email_verified_client_verification_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(default="Project Mizan", max_length=100),
                ),
                (
                    "openrouter_api_key",
                    models.CharField(
                        blank=True,
                        help_text="API Key for Basira AI (OpenRouter)",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "brevo_api_key",
                    models.CharField(
                        blank=True,
                        help_text="API Key for Brevo SMTP",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "brevo_email_sender",
                    models.EmailField(
                        default="noreply@project-mizan.com",
                        help_text="Default sender email address",
                        max_length=254,
                    ),
                ),
                (
                    "enable_registration",
                    models.BooleanField(
                        default=True, help_text="Allow new workspaces to register"
                    ),
                ),
                (
                    "maintenance_mode",
                    models.BooleanField(
                        default=False,
                        help_text="Enable maintenance mode (only admins can login)",
                    ),
                ),
            ],
            options={
                "verbose_name": "System Configuration",
                "verbose_name_plural": "System Configuration",
            },
        ),
    ]
