# Generated by Django 5.2.9 on 2026-01-03 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0010_staffrole_staffmember"),
    ]

    operations = [
        migrations.CreateModel(
            name="TelegramLink",
            fields=[
                (
                    "phone_number",
                    models.CharField(
                        max_length=20, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("chat_id", models.CharField(max_length=50)),
                ("linked_at", models.DateTimeField(auto_now_add=True)),
                ("is_verified", models.BooleanField(default=False)),
            ],
            options={
                "verbose_name": "Telegram Link",
                "verbose_name_plural": "Telegram Links",
            },
        ),
    ]
