# Generated by Django 5.2.9 on 2026-01-04 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0011_telegramlink"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipconfig",
            name="razorpay_key_id",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="razorpay_key_secret",
            field=models.CharField(blank=True, default="", max_length=50),
        ),
    ]
