# Generated by Django 5.2.9 on 2026-01-04 01:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0012_membershipconfig_razorpay_key_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipconfig",
            name="cashfree_app_id",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="cashfree_secret_key",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="payment_gateway_provider",
            field=models.CharField(
                choices=[
                    ("RAZORPAY", "Razorpay"),
                    ("CASHFREE", "Cashfree Payments"),
                    ("NONE", "None"),
                ],
                default="NONE",
                max_length=20,
            ),
        ),
    ]
