# Generated by Django 5.2.9 on 2026-01-04 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0013_membershipconfig_cashfree_app_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipconfig",
            name="organization_address",
            field=models.TextField(blank=True, help_text="Registered Address"),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="organization_name",
            field=models.CharField(
                default="Digital Jamath",
                help_text="Legal Name for Receipts",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="organization_pan",
            field=models.CharField(
                blank=True, help_text="Organization PAN", max_length=20
            ),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="registration_number_80g",
            field=models.CharField(
                blank=True, help_text="80G Registration Number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="receipt",
            name="donor_pan",
            field=models.CharField(
                blank=True, help_text="For 80G Compliance", max_length=15, null=True
            ),
        ),
    ]
