# Generated by Django 5.2.9 on 2026-01-04 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jamath", "0014_membershipconfig_organization_address_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="membershipconfig",
            name="telegram_auto_reminders",
            field=models.BooleanField(
                default=False,
                help_text="Automatically send payment reminders (via cron)",
            ),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="telegram_enabled",
            field=models.BooleanField(
                default=True, help_text="Enable Telegram notifications"
            ),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="telegram_notify_announcements",
            field=models.BooleanField(
                default=False, help_text="Auto-broadcast announcements when published"
            ),
        ),
        migrations.AddField(
            model_name="membershipconfig",
            name="telegram_notify_profile_updates",
            field=models.BooleanField(
                default=True, help_text="Notify members when their profile is updated"
            ),
        ),
    ]
